services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: registration_02
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  spring-app:
    build: .
    container_name: spring-app
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge